# Generated by Django 5.0.4 on 2024-04-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='bill_email',
            field=models.EmailField(default='ex@ex.com', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cashback',
            field=models.IntegerField(default=0, verbose_name='Кэшбек'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='ex@ex.com', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='password',
            field=models.CharField(default='pass', max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка по промокоду'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='final_price',
            field=models.IntegerField(default=0, verbose_name='Конечная стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='original_price',
            field=models.IntegerField(default=0, verbose_name='Полная стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('PAID', 'Оплачен'), ('ERROR', 'Ошибка'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Выполнен')], default='CREATED', verbose_name='Статус'),
        ),
    ]
