# Generated by Django 5.0.4 on 2024-04-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_orderproduct_price_order_bill_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='spend_cashback',
            field=models.BooleanField(default=False, verbose_name='Списать баллы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cashback',
            field=models.IntegerField(default=0, verbose_name='Кэшбек'),
        ),
    ]
