# Generated by Django 5.0.4 on 2024-05-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_spend_cashback_alter_order_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, null=True, verbose_name='ID платежа'),
        ),
    ]
