# Generated by Django 5.0.4 on 2024-05-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymnet_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
