# Generated by Django 5.0.4 on 2024-05-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_paymnet_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymnet_url',
            new_name='payment_url',
        ),
    ]
