version: '3.1'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8100:80"
    volumes:
      - ./dev.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - product_parser
      - payments

  postgres:
    image: postgres:14-alpine3.17
    ports:
      - "5551:5432"
    env_file:
      - ./local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: registry.gitlab.com/chat-labs/aoki-bot/backend:latest
    depends_on:
      - postgres
      - redis
      - celery_worker
    env_file:
      - ./local.env
    environment:
      - PRODUCT_PARSER_HOST=product_parser
      - POSTGRES_HOST=postgres
    volumes:
      - ./backend:/backend
      - ./rsa:/backend/rsa
    command: sh -c "python manage.py makemigrations && \
                      python manage.py migrate && \
                      (python manage.py createsuperuser --username admin --email admin@mail.ru --noinput || true) && \
                      python manage.py collectstatic --noinput && \
                      nohup python start_service.py & \
                      wait"
  celery_worker:
    image: registry.gitlab.com/chat-labs/aoki-bot/backend:latest
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/backend
      - ./rsa:/backend/rsa
    env_file:
      - ./local.env
    command: celery -A settings worker --concurrency=2 --pool=threads --loglevel=info
    restart: unless-stopped

  celery_beat:
    image: registry.gitlab.com/chat-labs/aoki-bot/backend:latest
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/backend
      - ./rsa:/backend/rsa
    env_file:
      - ./local.env
    command: celery -A settings beat --loglevel=info
    restart: unless-stopped

  product_parser:
    image: registry.gitlab.com/chat-labs/aoki-bot/product_parser:latest
    build: product_parser/
    depends_on:
      - postgres
      - backend
    env_file:
      - ./local.env
    volumes:
      - ./product_parser:/product_parser
    environment:
      - BACKEND_HOST=backend
    command: [ "python", "main.py" ]
    restart: unless-stopped

  payments:
    image: registry.gitlab.com/chat-labs/aoki-bot/payments:latest
    depends_on:
      - postgres
      - backend
    env_file:
      - ./local.env
    volumes:
      - ./payments:/payments
    command: [ "python", "main.py" ]
    restart: unless-stopped
  
  frontend:
    image: registry.gitlab.com/chat-labs/aoki-bot/frontend:latest
    env_file:
      - ./local.env
    ports:
      - "8050:8050"
    command: [ "serve", "-s", "dist", "-l", "8050" ]

  tg_bot:
    image: registry.gitlab.com/chat-labs/aoki-bot/tg_bot:latest
    env_file:
      - ./local.env
    volumes:
      - ./tg_bot:/tg_bot
    command: [ "python", "main.py" ]

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped


  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/3
      - FLOWER_PORT=8888
    ports:
      - 8889:8888
    depends_on:
      - redis

volumes:
  postgres_data:
