version: '3.1'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8100:80"
    volumes:
      - ./dev.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - product_parser
      - payments
      
  postgres:
    image: postgres:14-alpine3.17
    ports:
      - "5551:5432"
    env_file:
      - ./local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: registry.gitlab.com/chat-labs/aoki-bot/backend:latest
    build: backend/
    depends_on:
      - postgres
      - redis
    env_file:
      - ./local.env
    environment:
      - PRODUCT_PARSER_HOST=product_parser
      - POSTGRES_HOST=postgres
    volumes:
      - ./backend:/backend
      - ./rsa:/backend/rsa
    command: sh -c "python manage.py makemigrations --no-input && python manage.py migrate && (python manage.py createsuperuser --username admin --email admin@mail.ru --noinput || true) && python manage.py collectstatic --noinput && python start_service.py"


  product_parser:
    image: registry.gitlab.com/chat-labs/aoki-bot/product_parser:latest
    depends_on:
      - postgres
      - backend
    env_file:
      - ./local.env
    environment:
      - BACKEND_HOST=backend
    command: [ "python", "main.py" ]


  payments:
    image: registry.gitlab.com/chat-labs/aoki-bot/payments:latest
    depends_on:
      - postgres
      - backend
    env_file:
      - ./local.env
    volumes:
      - ./payments:/payments
    command: [ "python", "main.py" ]

  
  frontend:
    image: registry.gitlab.com/chat-labs/aoki-bot/frontend:latest
    env_file:
      - ./local.env
    ports:
      - "8050:8050"
    command: [ "serve", "-s", "dist", "-l", "8050" ]

  tg_bot:
    image: registry.gitlab.com/chat-labs/aoki-bot/tg_bot:latest
    env_file:
      - ./local.env
    command: [ "python", "main.py" ]

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  postgres_data:
