version: '3.1'
services:
  postgres:
    image: postgres:14-alpine3.17
    ports:
      - "5533:5432"
    env_file:
      - ./local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: .
    depends_on:
      - postgres
    env_file:
      - ./local.env
    volumes:
      - .:/app
    command: [ "sh", "start.sh" ]
    ports:
      - "8000:8000"

volumes:
  postgres_data:
