version: '3.1'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - product_parser
      - payments
      
  postgres:
    image: postgres:14-alpine3.17
    env_file:
      - ./local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: $CI_REGISTRY_IMAGE/backend
    depends_on:
      - postgres
    env_file:
      - ./local.env
    environment:
      - PRODUCT_PARSER_HOST=product_parser
      - POSTGRES_HOST=postgres
    volumes:
      - ./backend:/backend
      - ./rsa:/backend/rsa
    command: [ "python", "start_service.py" ]
    ports:
      - "8080:8080"

  product_parser:
    image: $CI_REGISTRY_IMAGE/product_parser
    depends_on:
      - postgres
      - backend
    env_file:
      - ./local.env
    environment:
      - BACKEND_HOST=backend
    command: [ "python", "main.py" ]
    ports:
      - "8090:8090"

  payments:
    image: $CI_REGISTRY_IMAGE/payments
    depends_on:
      - postgres
      - backend
    env_file:
      - ./local.env
    command: [ "python", "main.py" ]
    ports:
      - "8086:8086"
  
  frontend:
    image: $CI_REGISTRY_IMAGE/frontend
    env_file:
      - ./local.env
    volumes:
      - ./frontend:/frontend
    command: [ "serve", "-s", "dist", "-l", "8050" ]
    ports:
      - "8050:8050"
