# Generated by Django 5.0.4 on 2024-04-19 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен в')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен в')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен в')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('type', models.CharField(choices=[('GAME', 'Игра'), ('SUBSCRIPTION', 'Подписка'), ('DONATION', 'Донат')], max_length=32, verbose_name='Тип')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('language', models.ManyToManyField(to='api.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен в')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('includes', models.TextField(blank=True, null=True, verbose_name='Включает')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('cashback', models.IntegerField(blank=True, null=True, verbose_name='Кэшбек')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('platform', models.ManyToManyField(to='api.platform', verbose_name='Платформа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='api.product', verbose_name='Товар')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен в')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('database_name', models.CharField(max_length=255, verbose_name='Системное название')),
                ('product', models.ManyToManyField(related_name='tag', to='api.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
