# Generated by Django 5.0.4 on 2024-04-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpublication',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность в месяцах'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество игровой валюты'),
        ),
    ]
