# Generated by Django 5.0.4 on 2024-04-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productpublication_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(null=True, related_name='tag', to='api.product', verbose_name='Товар'),
        ),
    ]
