# Generated by Django 5.0.4 on 2024-04-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tag_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpublication',
            options={'verbose_name': 'Издание', 'verbose_name_plural': 'Издания'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='language',
        ),
        migrations.RemoveField(
            model_name='productpublication',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='languages',
            field=models.ManyToManyField(to='api.language', verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='productpublication',
            name='platforms',
            field=models.ManyToManyField(to='api.platform', verbose_name='Платформы'),
        ),
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='tag', to='api.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Длительность в месяцах'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Количество игровой валюты'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
