# Generated by Django 5.0.4 on 2024-04-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_productpublication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpublication',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка %'),
        ),
        migrations.AddField(
            model_name='productpublication',
            name='discount_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание скидки'),
        ),
        migrations.AddField(
            model_name='productpublication',
            name='ps_plus_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка PS Plus %'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='cashback',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кэшбек %'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='tags', to='api.product', verbose_name='Товары'),
        ),
    ]
