# Generated by Django 5.0.4 on 2024-04-18 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_alter_donation_options_alter_donation_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpublication',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(default='8226a736-8c9a-4ed5-b554-091dcbcbffd8', on_delete=django.db.models.deletion.CASCADE, to='api.type'),
            preserve_default=False,
        ),
    ]
