# Generated by Django 5.0.4 on 2024-04-22 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productpublication_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен в')),
                ('date', models.DateField(verbose_name='Дата заказа')),
                ('amount', models.IntegerField(verbose_name='Сумма заказа')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен в')),
                ('telegram_id', models.IntegerField(verbose_name='Телеграм ID')),
                ('playstation_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail от аккаунта PlayStation')),
                ('playstation_password', models.CharField(blank=True, null=True, verbose_name='Пароль от аккаунта PlayStation')),
                ('bill_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail для чеков')),
                ('cashback', models.IntegerField(default=0, verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен в')),
                ('item', models.CharField(max_length=255, verbose_name='Позиция')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='api.orders', verbose_name='Заказ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
