# Generated by Django 5.0.4 on 2024-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_orders_profile_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_seed',
            field=models.IntegerField(default=0, verbose_name='Семя токена'),
        ),
    ]
