# Generated by Django 5.0.4 on 2024-04-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tag_alter_productpublication_product_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
