# Generated by Django 5.0.4 on 2024-04-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_token_seed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
