# Generated by Django 5.0.4 on 2024-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_orders_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OK', 'Ок'), ('PAID', 'Оплачен'), ('ERROR', 'Ошибка')], default='OK', verbose_name='Статус'),
        ),
    ]
