# Generated by Django 5.0.4 on 2024-04-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_producttag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='database_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
