# Generated by Django 5.0.4 on 2024-04-19 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_producttag_title_tag_database_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpublication',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='api.product'),
        ),
        migrations.DeleteModel(
            name='ProductDuration',
        ),
    ]
