# Generated by Django 5.0.4 on 2024-04-22 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='token_seed',
        ),
        migrations.AddField(
            model_name='profile',
            name='token_expiraton',
            field=models.DateTimeField(auto_now=True, verbose_name='Семя токена'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='api.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.IntegerField(unique=True, verbose_name='Телеграм ID'),
        ),
    ]
