# Generated by Django 5.0.4 on 2024-04-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_profile_token_seed_profile_token_expiraton_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='token_expiraton',
        ),
    ]
