# Generated by Django 5.0.4 on 2024-04-22 18:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_profile_token_expiraton'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_seed',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Семя токена'),
        ),
    ]
