# Generated by Django 5.0.4 on 2024-04-23 00:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_token_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен в')),
                ('promo_code', models.CharField(max_length=255, verbose_name='Промокод')),
                ('expiration', models.DateTimeField(verbose_name='Дата окончания')),
                ('discount', models.IntegerField(verbose_name='Скидка %')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
