# Generated by Django 5.0.4 on 2024-04-23 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ps_store_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка в PS Store'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='cashback',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Кэшбек %'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка %'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='ps_plus_discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка PS Plus %'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка %'),
        ),
    ]
