# Generated by Django 5.0.4 on 2024-04-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_product_ps_store_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='item',
            new_name='product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_id',
            field=models.CharField(default='08ea7d6c-f4fd-4dfa-9d38-2184192d8365', max_length=255, verbose_name='ID товара'),
            preserve_default=False,
        ),
    ]
