# Generated by Django 5.0.4 on 2024-04-25 19:24

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_item_orderproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpublication',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='preview',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
