# Generated by Django 5.0.4 on 2024-04-26 01:52

import django.db.models.deletion
import imagekit.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_productpublication_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpublication',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='preview',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен в')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='api.profile', verbose_name='Сообщение')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
