# Generated by Django 5.0.4 on 2024-04-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_productpublication_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='profile',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='order',
            field=models.ForeignKey(default='f59a6f47-e11d-4a72-94db-059eae8a0b93', on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='api.order', verbose_name='Сообщение'),
            preserve_default=False,
        ),
    ]
