# Generated by Django 5.0.4 on 2024-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_chatmessage_profile_chatmessage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpublication',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэш'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность в месяцах'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество игровой валюты'),
        ),
        migrations.AlterField(
            model_name='productpublication',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
