# Generated by Django 5.0.4 on 2024-04-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_productpublication_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpublication',
            name='price',
        ),
        migrations.AddField(
            model_name='productpublication',
            name='final_price',
            field=models.IntegerField(default=0, verbose_name='Конечная стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpublication',
            name='original_price',
            field=models.IntegerField(default=0, verbose_name='Полная стоимость'),
            preserve_default=False,
        ),
    ]
