# Generated by Django 5.0.4 on 2024-04-26 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_productpublication_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpublication',
            name='cashback',
            field=models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Кэшбек %'),
        ),
    ]
