# Generated by Django 5.0.4 on 2024-04-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_productpublication_cashback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Телеграм ID'),
        ),
    ]
